### ISSUE TITLE
vim.editor not working - possibly incomplete?

### ISSUE THREAD

**Issue by zatricky** [saltstack-formulas/vim-formula#13]
I'm new at salt - so I'm not sure if I'm doing something wrong or if the feature simply isn't complete.

When attempting to use vim.editor I get the following error:

Rendering SLS 'base:vim.editor' failed: Jinja variable 'map' is undefined

**Comment by gravyboat** [comment]
@zatricky I've resolved this over in #14. There were just some missing " around the vim/map.jinja. Feel free to make that change in your local repo if you don't want to wait. Otherwise once my PR is merged in you can do a pull from upstream.

**Comment by gravyboat** [comment]
@zatricky I'm closing this as #14 has been merged in.
